[tox]
envlist = py38,py39,py310,py311,py312

[testenv]
deps = .
commands =
    python -m unittest discover
    taxit -v new_database
commands_post =
    python -c "import os; [os.remove(f) for f in ['ncbi_taxonomy.db', 'taxdmp.zip'] if os.path.exists(f)]"

[flake8]
exclude = .tox,*.egg,build
ignore = E501,E265,W391
