Bootstrap:docker
From:python:3.6.7-stretch

%setup
  mkdir ${SINGULARITY_ROOTFS}/src

%files
  taxtastic.tar.gz /src/taxtastic.tar.gz
  install_pplacer.sh /usr/local/bin/install_pplacer.sh

%post
  apt-get update
  apt-get install -y unzip --no-install-recommends
  /usr/local/bin/install_pplacer.sh /usr/local 1.1.alpha19
  rm -rf /var/lib/apt/lists/*
  apt-get purge -y --auto-remove unzip
  pip install /src/taxtastic.tar.gz
  mkdir -p /app /fh /mnt /run/shm  # create bind points
